# Generated by Django 4.1 on 2022-09-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("foto", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Pereval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(default="пер.", max_length=10)),
                ("title", models.CharField(max_length=25)),
                ("other_titles", models.CharField(max_length=25)),
                ("connect", models.CharField(blank=True, max_length=25)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                ("level_winter", models.CharField(blank=True, max_length=2)),
                ("level_summer", models.CharField(blank=True, max_length=2)),
                ("level_autumn", models.CharField(blank=True, max_length=2)),
                ("level_spring", models.CharField(blank=True, max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "модерация прошла успешно"),
                            ("RJ", "модерация прошла, информация не принята"),
                            ("NW", "новый"),
                            ("PD", "принято на модерацию"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=9)),
                ("surname", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=15)),
                ("patronymic", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="PerevalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perevel.image"
                    ),
                ),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevel.pereval",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pereval",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="perevel.user"
            ),
        ),
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.IntegerField()),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perevel.pereval",
                    ),
                ),
            ],
        ),
    ]
